[package]
name = "spucky"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "1.0.107", features = ["parsing", "full"] }

[dev-dependencies]
serial_test ="1.0.0"